{"name": "test_equality", "status": "failed", "statusDetails": {"message": "AssertionError: assert 10 == 11", "trace": "@pytest.mark.others\n    def test_equality():\n>       assert 10 == 11\nE       assert 10 == 11\n\ntest_square.py:17: AssertionError"}, "start": 1602843563804, "stop": 1602843563804, "uuid": "b9cfc071-2a40-40ff-82c7-1b5eef7ad797", "historyId": "3d2cb46673a5ec877a01c9c6a507b500", "testCaseId": "2cd0ec3053a202c03e594cd508a5cddb", "fullName": "test_square#test_equality", "labels": [{"name": "tag", "value": "others"}, {"name": "suite", "value": "test_square"}, {"name": "host", "value": "DESKTOP-PCEHKV8"}, {"name": "thread", "value": "14752-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_square"}]}